# Generated by Django 3.2.21 on 2023-10-01 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_dob_student_date_of_birth'),
        ('checkout', '0004_order_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='student',
            field=models.ForeignKey(blank=True, default=34, on_delete=django.db.models.deletion.CASCADE, to='profiles.student'),
            preserve_default=False,
        ),
    ]
