# Generated by Django 3.2.21 on 2023-09-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('GR', 'groups'), ('IN', 'individual'), ('CA', 'camps')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('SH', 'seahorse_begginers'), ('JF', 'jellyfish_floaters'), ('TG', 'turtle_gliders'), ('DD', 'dolphin_divers'), ('SS', 'shark_speedsters')], default='SH', max_length=2)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('day_of_the_week', models.CharField(choices=[('MO', 'monday'), ('TU', 'tuesday'), ('WE', 'wednesday'), ('TH', 'thrusday'), ('FR', 'friday'), ('SA', 'saturday'), ('SU', 'sunday')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('places', models.PositiveIntegerField(default=6)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.category')),
            ],
        ),
    ]
