# Generated by Django 3.2.21 on 2023-09-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('GROUP', 'groups'), ('INDIVIDUAL', 'individual'), ('CAMPS', 'camps')], max_length=15)),
                ('description', models.TextField(default='blank')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('SEAHORSE_BEGGINERS', 'seahorse_begginers'), ('JELLYFISH_FLOATER', 'jellyfish_floaters'), ('TURTLE_GLIDERS', 'turtle_gliders'), ('DOLPHIN_DIVERS', 'dolphin_divers'), ('SHARK_SPEEDSTERS', 'shark_speedsters')], default='SEAHORSE_BEGGINERS', max_length=30)),
                ('who_for', models.TextField(default='blank')),
                ('skills', models.TextField(default='blank')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='blank', max_length=250)),
                ('description', models.TextField(default='blank')),
                ('duration', models.TextField(default='blank')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('day_of_the_week', models.CharField(choices=[('MONDAY', 'monday'), ('TUESDAY', 'tuesday'), ('WEDNESDAY', 'wednesday'), ('THRUSDAY', 'thrusday'), ('FRIDAY', 'friday'), ('SATURDAY', 'saturday'), ('SUNDAY', 'sunday')], max_length=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('places', models.PositiveIntegerField(default=6)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.category')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.levels')),
            ],
        ),
    ]
