# Generated by Django 3.2.21 on 2023-09-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='blank'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='blank'),
        ),
    ]
