# Generated by Django 3.2.21 on 2023-09-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_day_of_the_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.TextField(default='blank'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(),
        ),
    ]
