# Generated by Django 3.2.21 on 2023-09-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20230924_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day_of_the_week',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THRUSDAY', 'Thrusday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('WEEKLY', 'Mon-Fri')], max_length=12),
        ),
    ]
