# Generated by Django 3.2.21 on 2023-10-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20230925_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day_of_the_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thrusday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Mon-Fri', 'Mon-Fri')], max_length=12),
        ),
        migrations.AlterField(
            model_name='levels',
            name='level',
            field=models.CharField(choices=[('Seahorse_Begginers', 'Seahorse_Begginers'), ('Jellyfish_Floater', 'Jellyfish_Floaters'), ('Turtle_Gliders', 'turtle_Gliders'), ('Dolphins_Divers', 'Dolphin_Divers'), ('Shark_Speedster', 'Shark_Speedsters'), ('Personalised', 'Personalised')], default='Seahorse_Begginers', max_length=30),
        ),
    ]
