# Generated by Django 3.2.21 on 2023-10-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20231001_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.TextField(default='Course duration'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='Course Name', max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TextField(default='Enter start time'),
        ),
    ]
